/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAbout: typeof import('./components/TheAbout.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheEducation: typeof import('./components/TheEducation.vue')['default']
    TheExperience: typeof import('./components/TheExperience.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheNavBtn: typeof import('./components/TheNavBtn.vue')['default']
    TheProjects: typeof import('./components/TheProjects.vue')['default']
    TheSkills: typeof import('./components/TheSkills.vue')['default']
  }
}
